services:
  - type: web
    name: medicine-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false  # Set this manually in Render's dashboard
